INSERT INTO `forums`.`users`(`source_id`, `nickname`, `email`, `label`, `created_at`) VALUES 
(122, '立春', 'test1@123.com', 'test1', now()),
(123, '雨水', 'test2@123.com', 'test2', now()),
(124, '雨水', 'test25@123.com','test',  now()),
(125, '惊蛰', 'test3@123.com', 'test', now()),
(126, '春分', 'test4@123.com', 'test', now()),
(127, '清明', 'test5@123.com', 'test', now()),
(128, '谷雨', 'test6@123.com', 'test', now()),
(129, '立夏', 'test7@123.com', 'test', now()),
(130, '小满', 'test8@123.com', 'test', now()),
(131, '芒种', 'test9@123.com', 'test', now()),
(132, '夏至', 'test10@123.com', 'test', now()),
(133, '小暑', 'test11@123.com', 'test', now()),
(134, '大暑', 'test12@123.com', 'test', now()),
(135, '立秋', 'test13@123.com', 'test', now()),
(136, '处暑', 'test14@123.com', 'test', now()),
(137, '白露', 'test15@123.com', 'test', now()),
(138, '秋分', 'test16@123.com', 'test', now()),
(139, '寒露', 'test17@123.com', 'test', now()),
(140, '霜降', 'test18@123.com', 'test', now()),
(141, '立冬', 'test19@123.com', 'test', now()),
(142, '小雪', 'test20@123.com', 'test', now()),
(143, '大雪', 'test21@123.com', 'test', now()),
(144, '冬至', 'test22@123.com', 'test', now()),
(145, '小寒', 'test23@123.com', 'test', now()),
(146, '大寒', 'test24@123.com', 'test', now());

INSERT INTO `forums`.`system_message_template`(`msg_type`, `msg_body`, `msg_title`, `created_at`) VALUES
(10, '您的{{square_name}}广场创建申请已通过', '广场创建', now()),
(11, '您的{{square_name}}广场创建申请已驳回', '广场创建', now()),
(12, '您对{{user_name}}的投诉已被驳回', '投诉', now()),
(13, '您对{{user_name}}的投诉已被受理，我们已对该用户进行处理', '投诉', now()),
(14, '您的广播{{title}}由于被投诉已被管理员删除', '被投诉', now()),
(15, '您的广播{{title}}由于被投诉已被管理员删除，并且您被禁言7天', '被投诉', now()),
(16, '您的广播{{title}}由于被投诉已被管理员删除，并且您被永久禁言', '被投诉', now()),
(17, '您的回复{{content}}由于被投诉已被管理员删除', '被投诉', now()),
(18, '您的回复{{content}}由于被投诉已被管理员删除，并且您被禁言7天', '被投诉', now()),
(19, '您的回复{{content}}由于被投诉已被管理员删除，并且您被永久禁言', '被投诉', now()),
(20, '{{user_name}}点赞了您的广播{{title}}', '广播被点赞', now()),
(21, '{{user_name}}点赞了您的回复{{content}}', '回复被点赞', now()),
(22, '{{user_name}}回复了您的广播{{title}}', '广播被回复', now()),
(23, '{{user_name}}回复了您的回复{{content}}', '回复被回复', now()),
(24, '{{user_name}}关注了您', '被关注', now()),
(25, '您的广播{{title}}已被管理员在{{square_name}}置顶', '广播置顶', now()),
(26, '您的广播{{title}}已被管理员在首页置顶', '广播置顶', now()),
(27, '您的广播{{title}}已被广场主在{{square_name}}置顶', '广播置顶', now()),
(28, '您的广播{{title}}已被管理员删除', '广播被删除', now()),
(29, '您的广播{{title}}已被广场主删除', '广播被删除', now()),
(30, '您的回复{{content}}已被管理员删除', '回复被删除', now()),
(31, '您的回复{{content}}已被广场主删除', '回复被删除', now()),
(32, '您的{{square_name}}的卸任申请已被通过', '卸任广场主（本人）', now()),
(33, '您的{{square_name}}的卸任申请已被驳回', '卸任广场主（本人）', now()),
(34, '您关注的{{square_name}}广场主已变更为{{user_name}}', '卸任广场主本广场的关注用户', now()),
(35, '您在{{square_name}}已被用户多次投诉，请认真履行广场主的责任，如不加以改正，管理员可能会卸任您的广场主权限', '广场主被投诉', now());


